Modificadas las pruebas que se deben ejecutar. Surgen nuevos errores.
Failures:

  1) Fraccion# Funciones de conversion Debe mostrar la fraccion en formato flotante
     Failure/Error: @f1.to_f.should eq(1.0)
     NoMethodError:
       undefined method `to_f' for 1/1:Fraccion
     # ./spec/frac_spec.rb:47:in `block (3 levels) in <top (required)>'

  2) Fraccion# Funciones de calculo Debe calcular el valor absoluto de la funcion con abs
     Failure/Error: @f4.abs.should eq(Fraccion.new(12,6))
     NoMethodError:
       undefined method `num' for 2.0:Float
     # ./lib/fraccion.rb:18:in `=='
     # ./spec/frac_spec.rb:59:in `block (3 levels) in <top (required)>'

Finished in 0.00271 seconds
9 examples, 2 failures