Añadido el test para el operador <=.
  1) Fraccion# Funciones de comparacion Se debe de poder comprobar si una fraccion es menor o igual que otra
     Failure/Error: @f1.should_not be <= @f2
     NoMethodError:
       undefined method `<=' for 1/1:Fraccion
     # ./spec/frac_spec.rb:105:in `block (3 levels) in <top (required)>'

Finished in 0.00533 seconds
18 examples, 1 failure