Añadido el test de la división entre fracciones.
Failures:

  1) Fraccion# Funciones de calculo Debe hacer el cociente entre dos fracciones y dar el resultado reducido
     Failure/Error: (@f2 / @f3).should eq(Fraccion.new(4,15))
     NoMethodError:
       undefined method `/' for 2/3:Fraccion
     # ./spec/frac_spec.rb:88:in `block (3 levels) in <top (required)>'

Finished in 0.00337 seconds
15 examples, 1 failure