Añadido el test para calcular el inverso de la fracción.
Failures:

  1) Fraccion# Funciones de conversion Debe poder calcular el opuesto de una fraccion
     Failure/Error: (-@f1).should eq(Fraccion.new(-1,1))
     NoMethodError:
       undefined method `-@' for 1/1:Fraccion
     # ./spec/frac_spec.rb:62:in `block (3 levels) in <top (required)>'

Finished in 0.0029 seconds
11 examples, 1 failure