Añadido el test que intenta acceder al denominador mediante el método denom()
Failures:

  1) Fraccion# Acceso a las variables Debe permitir el acceso al denominador mediante el metodo denom()
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `denom' for #<Fraccion:0x000000024fe708 @d=1, @num=1>
     # ./spec/frac_spec.rb:33:in `block (3 levels) in <top (required)>'

Finished in 0.00126 seconds
5 examples, 1 failure

Failed examples:

rspec /usr/lib/ruby/vendor_ruby/rspec/core/metadata.rb:164 # Fraccion# Acceso a las variables Debe permitir el acceso al denominador mediante el metodo denom()