Modificado el nombre del atributo para pasar el nuevo test. Fallan los tests anteriores por el cambio de nombre.
Failures:

  1) Fraccion Debe estar en su forma reducida
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `d' for #<Fraccion:0x0000000286efc8 @denom=2, @num=1>
     # ./spec/frac_spec.rb:24:in `block (2 levels) in <top (required)>'

  2) Fraccion#Comprobacion de variables Hay denominador
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `d' for #<Fraccion:0x00000002714830 @denom=1, @num=1>
     # ./spec/frac_spec.rb:17:in `block (3 levels) in <top (required)>'

Finished in 0.00127 seconds
5 examples, 2 failures

Failed examples:

rspec /usr/lib/ruby/vendor_ruby/rspec/core/metadata.rb:164 # Fraccion Debe estar en su forma reducida
rspec /usr/lib/ruby/vendor_ruby/rspec/core/metadata.rb:164 # Fraccion#Comprobacion de variables Hay denominador