Cambiado nombre del atributo para pasar el test. Algunos de los tests anteriores fallan porque ahora el nombre del atributo está cambiado.
Failures:

  1) Fraccion Debe estar en su forma reducida
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `n' for #<Fraccion:0x000000029e1ce8 @d=2, @num=1>
     # ./spec/frac_spec.rb:23:in `block (2 levels) in <top (required)>'

  2) Fraccion#Comprobacion de variables Hay numerador
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `n' for #<Fraccion:0x00000002b2b090 @d=1, @num=1>
     # ./spec/frac_spec.rb:13:in `block (3 levels) in <top (required)>'

Finished in 0.00112 seconds
4 examples, 2 failures

Failed examples:

rspec /usr/lib/ruby/vendor_ruby/rspec/core/metadata.rb:164 # Fraccion Debe estar en su forma reducida
rspec /usr/lib/ruby/vendor_ruby/rspec/core/metadata.rb:164 # Fraccion#Comprobacion de variables Hay numerador