Añadido test de la resta.
Failures:

  1) Fraccion# Funciones de calculo Debe hacer la resta entre dos fracciones y dar el resultado reducido
     Failure/Error: (@f2 - @f3).should eq(Fraccion.new(-11,6))
     NoMethodError:
       undefined method `-' for 2/3:Fraccion
     # ./spec/frac_spec.rb:78:in `block (3 levels) in <top (required)>'

Finished in 0.00329 seconds
13 examples, 1 failure