Añadido test para el recíproco.
Failures:

  1) Fraccion# Funciones de conversion Debe calcular el reciproco de una fraccion
     Failure/Error: @f2.rec.should eq(Fraction.new(3,2))
     NoMethodError:
       undefined method `rec' for 2/3:Fraccion
     # ./spec/frac_spec.rb:57:in `block (3 levels) in <top (required)>'

Finished in 0.00268 seconds
10 examples, 1 failure