Añadido el test para el producto de fracciones.
Failures:

  1) Fraccion# Funciones de calculo Debe hacer el product entre dos fracciones y dar el resultado reducido
     Failure/Error: (@f2 * @f3).should eq(Fraccion.new(5,3))
     NoMethodError:
       undefined method `*' for 2/3:Fraccion
     # ./spec/frac_spec.rb:83:in `block (3 levels) in <top (required)>'

Finished in 0.00329 seconds
14 examples, 1 failure