Test para el operador >= añadido.
  1) Fraccion# Funciones de comparacion Se debe de poder comprobar si una fraccion es mayor o igual que otra
     Failure/Error: @f2.should_not be >= @f1
     NoMethodError:
       undefined method `>=' for 2/3:Fraccion
     # ./spec/frac_spec.rb:111:in `block (3 levels) in <top (required)>'

Finished in 0.00508 seconds
19 examples, 1 failure