Test para el operador >.
  1) Fraccion# Funciones de comparacion Se debe de poder comprobar si una fraccion es mayor que otra
     Failure/Error: @f2.should be > @f4
     NoMethodError:
       undefined method `>' for 2/3:Fraccion
     # ./spec/frac_spec.rb:100:in `block (3 levels) in <top (required)>'

Finished in 0.00512 seconds
17 examples, 1 failure