Test para la suma añadido.
Failures:

  1) Fraccion# Funciones de calculo Debe hacer la suma entre dos fracciones y dar el resultado reducido
     Failure/Error: (@f2 + @f3).should eq(Fraccion.new(19,6))
     NoMethodError:
       undefined method `+' for 2/3:Fraccion
     # ./spec/frac_spec.rb:73:in `block (3 levels) in <top (required)>'

Finished in 0.00347 seconds
12 examples, 1 failure