Añadida la prueba que intenta acceder al método num().
Failures:

  1) Fraccion# Acceso a las variables Debe permitir el acceso al numerador mediante el metodo num()
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `num' for #<Fraccion:0x00000001e33cc0 @d=1, @n=1>
     # ./spec/frac_spec.rb:29:in `block (3 levels) in <top (required)>'

Finished in 0.00111 seconds
4 examples, 1 failure

Failed examples:

rspec /usr/lib/ruby/vendor_ruby/rspec/core/metadata.rb:164 # Fraccion# Acceso a las variables Debe permitir el acceso al numerador mediante el metodo num()